# Generated by Django 5.2.17 on 2026-10-01 15:56

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oracle_id', models.UUIDField(unique=True)),
                ('scryfall_id', models.UUIDField()),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('mana_cost', models.CharField(blank=True, max_length=100)),
                ('cmc', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('type_line', models.CharField(blank=True, max_length=300)),
                ('oracle_text', models.TextField(blank=True)),
                ('color_identity', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('W', 'White'), ('U', 'Blue'), ('B', 'Black'), ('R', 'Red'), ('G', 'Green')], max_length=1), blank=True, default=list, size=None)),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('W', 'White'), ('U', 'Blue'), ('B', 'Black'), ('R', 'Red'), ('G', 'Green')], max_length=1), blank=True, default=list, size=None)),
                ('price_cents', models.IntegerField(blank=True, null=True)),
                ('price_updated', models.DateTimeField(blank=True, null=True)),
                ('legal_commander', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('edhrec_rank', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_land', models.BooleanField(default=False)),
                ('is_basic', models.BooleanField(default=False)),
                ('can_be_commander', models.BooleanField(default=False)),
                ('layout', models.CharField(blank=True, max_length=40)),
                ('image_uri', models.URLField(blank=True, max_length=500)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['color_identity'], name='cards_card_color_i_4459b9_gin'), models.Index(fields=['legal_commander', 'edhrec_rank'], name='card_legal_rank_idx'), models.Index(fields=['can_be_commander'], name='card_is_commander_idx')],
            },
        ),
    ]
