# Generated by Django 5.2.17 on 2026-10-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cmc',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=12),
        ),
    ]
