# Generated by Django 5.2.17 on 2026-10-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_cmc'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='primary_role',
            field=models.CharField(choices=[('land', 'Land'), ('ramp', 'Ramp'), ('draw', 'Card draw'), ('spot_removal', 'Spot removal'), ('sweeper', 'Sweeper'), ('tutor', 'Tutor'), ('recursion', 'Recursion'), ('protection', 'Protection'), ('wincon', 'Win condition'), ('synergy', 'Synergy')], db_index=True, default='synergy', max_length=20),
        ),
        migrations.AddField(
            model_name='card',
            name='role_source',
            field=models.CharField(default='', help_text="'heuristic' or 'override' -- where this role came from.", max_length=10),
        ),
        migrations.AddField(
            model_name='card',
            name='secondary_role',
            field=models.CharField(blank=True, choices=[('land', 'Land'), ('ramp', 'Ramp'), ('draw', 'Card draw'), ('spot_removal', 'Spot removal'), ('sweeper', 'Sweeper'), ('tutor', 'Tutor'), ('recursion', 'Recursion'), ('protection', 'Protection'), ('wincon', 'Win condition'), ('synergy', 'Synergy')], default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['primary_role', 'edhrec_rank'], name='card_role_rank_idx'),
        ),
    ]
